-- ═══════════════════════════════════════════════════════
-- yAp — Seed Data (Empty)
-- Run AFTER schema.sql
--
-- No test data — all users are real accounts created via sign-up
-- ═══════════════════════════════════════════════════════
